/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sw;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lskre
 */
public class passwordChange extends javax.swing.JFrame {

    /**
     * Creates new form passwordChange
     */
    public passwordChange() {
        setUndecorated(true);
        initComponents();
        Color grey1 = new Color(240,240,240);
        jPasswordField1.setCaretColor(grey1);
        jPasswordField2.setCaretColor(grey1);
        jPasswordField3.setCaretColor(grey1);
		errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1006, 596));
        jPanel1.setMinimumSize(new java.awt.Dimension(1006, 596));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMaximumSize(new java.awt.Dimension(370, 277));
        jPanel2.setMinimumSize(new java.awt.Dimension(370, 277));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Change password");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(97, 272, 119, 17);

        jPasswordField1.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.setOpaque(false);
        jPasswordField1.setRequestFocusEnabled(false);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(97, 112, 285, 16);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(97, 130, 285, 15);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("OLD PASSWORD");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(97, 85, 117, 20);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("PASSWORD CHANGE");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 31, 175, 22);

        jPasswordField2.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField2.setBorder(null);
        jPasswordField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField2.setOpaque(false);
        jPasswordField2.setRequestFocusEnabled(false);
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(97, 172, 285, 16);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(97, 190, 285, 15);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("NEW PASSWORD");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(97, 145, 120, 20);

        jPasswordField3.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField3.setBorder(null);
        jPasswordField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField3.setOpaque(false);
        jPasswordField3.setRequestFocusEnabled(false);
        jPasswordField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField3MouseClicked(evt);
            }
        });
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField3);
        jPasswordField3.setBounds(97, 232, 285, 16);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(97, 250, 285, 15);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("RETYPE NEW PASSWORD");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(97, 205, 170, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Back");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(351, 272, 31, 17);

        errorLabel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Incorrect Password");
        errorLabel.setMaximumSize(new java.awt.Dimension(400, 20));
        errorLabel.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel2.add(errorLabel);
        errorLabel.setBounds(97, 307, 300, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(255, 99, 495, 381);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Close");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(957, 13, 37, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.requestFocus();
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.requestFocus();
        
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField3MouseClicked
        // TODO add your handling code here:
        jPasswordField3.requestFocus();
    }//GEN-LAST:event_jPasswordField3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(changePassword()){
			jPasswordField1.setText("");
			jPasswordField2.setText("");
			jPasswordField3.setText("");
			errorLabel.setForeground(new Color(240,240,240));
			errorLabel.setText("Passwrod Changed");
			errorLabel.setVisible(true);
		}
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        loginFrame newloginFrame = new loginFrame();
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        int keyPressed = evt.getKeyCode();
        if(keyPressed == java.awt.event.KeyEvent.VK_ENTER){
			if(changePassword()){
				jPasswordField1.setText("");
				jPasswordField2.setText("");
				jPasswordField3.setText("");
				errorLabel.setForeground(new Color(240,240,240));
				errorLabel.setText("Passwrod Changed");
				errorLabel.setVisible(true);
			}
		}
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
        int keyPressed = evt.getKeyCode();
        if(keyPressed == java.awt.event.KeyEvent.VK_ENTER){
			if(changePassword()){
				jPasswordField1.setText("");
				jPasswordField2.setText("");
				jPasswordField3.setText("");
				errorLabel.setForeground(new Color(240,240,240));
				errorLabel.setText("Passwrod Changed");
				errorLabel.setVisible(true);
			}
		}
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        // TODO add your handling code here:
        int keyPressed = evt.getKeyCode();
        if(keyPressed == java.awt.event.KeyEvent.VK_ENTER){
			if(changePassword()){
				jPasswordField1.setText("");
				jPasswordField2.setText("");
				jPasswordField3.setText("");
				errorLabel.setForeground(new Color(240,240,240));
				errorLabel.setText("Passwrod Changed");
				errorLabel.setVisible(true);
			}
		}
    }//GEN-LAST:event_jPasswordField3KeyPressed

    private boolean changePassword(){
        String inputPassword = new String(jPasswordField1.getPassword());
        String newInputPassword = new String(jPasswordField2.getPassword());
        String reInputPassword = new String(jPasswordField3.getPassword());
        
        System.out.println(inputPassword);
        System.out.println(newInputPassword);
        System.out.println(reInputPassword);
        passwordHandler passwordChecker = new passwordHandler();
        
        String filename = "src\\sw\\password.pswd";
        
        String salt;
        String actualHash;
        String inputHash;
        Boolean authenticated = false;
		Boolean changed = false;
        try {
            FileReader freader = new FileReader(filename);
            // Always wrap FileReader in BufferedReader.
            BufferedReader bufferedReader = new BufferedReader(freader);
            
            salt = bufferedReader.readLine();
            actualHash = bufferedReader.readLine();
			
            inputHash = passwordChecker.genSaltedHash(inputPassword, salt.getBytes());
	
            if(inputHash.equals(actualHash))
                authenticated = true;
			else{
				errorLabel.setVisible(true);
				authenticated = false;
			}
            System.out.println(authenticated);
            if(authenticated){
                if(newInputPassword.equals(reInputPassword)){
			passwordChecker.setPassword(newInputPassword);
			changed = true;
		}else{
				errorLabel.setText("New Passwords Donot Match");
				errorLabel.setVisible(true);
                }
            }
            // Always close files.
            bufferedReader.close();
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(loginFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(loginFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(loginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
		return changed;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passwordChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
